### ISSUE TITLE
Easy Overlay of QC in TimeSeries Plot

### ISSUE THREAD

**Issue by AdamTheisen** [ANL-DIGR/ACT#82]
Need an easy way to flag data based on QC variables in the TimeSeries plotting to start.  Something that we could pass a list of test numbers or a list of quality level (bad, suspect) and produce something like the attached plot.

<img width="1332" alt="Screen Shot 2019-07-10 at 11 44 22 AM" src="https://user-images.githubusercontent.com/13421074/60987999-5f924c80-a308-11e9-981b-4bf55feb80ec.png">

**Comment by kenkehoe** [comment]
Good idea. I have started to develop some code for this and have it implemented with our stuff with ECOR using a method in dqlib repo on code.arm.gov. I've started the work outside of ACT because it gets tricky. I've been using that to work out any issues with implementation. Maybe we can discuss this on the weekly call and see how best to implement. Some of the things I was working on fixing include:

- legend to explain colors for QC overlay data. I've set it up to add a legend to explain Bad and suspect in the legend. Can be an issue with multiple plotted lines that are using a legend because of default color selection.
- I have the code set up to use the standard ARM embedded QC. Since there are multiple assessment names used for embedded QC (Bad, Indeterminate) vs. DQRs (Incorrect, Suspect) I've set it up to look for all 4 but use Incorrect and Suspect on the plot.
- There are issues with adding the Incorrect and Suspect and a multi y axis plot.
- What should we do with 2-D plots?

**Comment by kenkehoe** [comment]
There is also a request to make the horizontal color bar plots that show embedded QC like DQ Inspector did. Do we add that to ACT or the new DQ Inspector replacement tool?

**Comment by AdamTheisen** [comment]
2D plots are hard, we could do what was done in DQ inspector and have a standalone QC plot available for creation.  I think the horizontal color bar plots could be a feature of a plot_bitpacked_qc plotting routine or something along those lines.

**Comment by AdamTheisen** [comment]
@kenkehoe do you want to tackle this as well if you're working on QC plots in #109 ??

**Comment by kenkehoe** [comment]
Afirm, I'll look into adding this code as well.

**Comment by kenkehoe** [comment]
Can you assign this to me?

**Comment by AdamTheisen** [comment]
Resolved with #118
